
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/shared/styles/general.scss'
import TanstackProvieder from '@/providers/TanstackProvieder';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Transactions Page',
	description: 'Generated by create next app',
}



export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (

		<html lang="en">
			<body className={inter.className}>
				<TanstackProvieder>
					{children}
				</TanstackProvieder>
			</body>
		</html>

	)
}
